src/sampleapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'sampleapp'
urlpatterns = [
	url(r'^$', views.index, name='index'),
]

src/system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^sampleapp/', include('sampleapp.urls')),
	url(r'^admin/', admin.site.urls),
]

src/sampleapp/models.py
from django.db import models

# Create your models here.

src/sampleapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'sampleapp.html')

src/system/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings

# Create your views here.
def index(request):
	context = {'settings_file': settings.CONFIG_FILE_IN_USE}
	return render(request, 'home.html', context)

src/sampleapp/templates/sampleapp.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content_outer %}
<h2>Sample app</h2>
<p><a href="{% url 'index' %}">&lt; Back to home page</a></p>
{% endblock %}

src/system/templates/base.html
{% load staticfiles %}<!doctype html>
<html>

<head>
	<title>Django Site Template</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
{% block content_outer %}
<h1>Django Site Template</h1>
{% block content %}{% endblock %}
{% endblock %}
</body>

</html>

src/system/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
<p>Current settings file: <b>{{ settings_file }}</b></p>
<p class="css-test" style="color:red">If this text is green, then "{% static 'css/base.css' %}" is working.</p>
<p><a href="{% url 'sampleapp:index' %}">Sample app</a></p>
{% endblock %}